version: 2
jobs:
  test:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    environment:
      GK_LOCK_DEFAULT_BRANCH: saga
    steps:
      - run:
          name: Run lint
          command: npx standard

      - run:
          name: Run tests
          command: npm test

      - run:
          when: on_success
          name: Run semantic relase
          command: |
            npm i --no-save semantic-release
            npx semantic-release || true

workflows:
  version: 2
  test:
    jobs:
      - test:
          context: bifravst
